# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.0
  - 1.1
  - nightly

notifications:
  email: false

addons:
  apt:
    packages:
    - gfortran

after_success:
  - julia -e 'using Pkg;
      cd(Pkg.dir("JAC"));
      Pkg.add("Coverage");
      using Coverage;
      Codecov.submit(process_folder());'
